import { bigint, boolean, integer, jsonb, pgTable, primaryKey, text, timestamp, uuid } from "drizzle-orm/pg-core";

export const guests = pgTable("guests", { id: uuid("id").primaryKey(), tokenHash: text("token_hash").notNull().unique(), nickname: text("nickname").notNull(), avatar: integer("avatar").notNull().default(0), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
export const tracks = pgTable("tracks", { id: text("id").primaryKey(), providerId: text("provider_id").notNull().unique(), title: text("title").notNull(), artist: text("artist").notNull(), artworkUrl: text("artwork_url"), duration: integer("duration").notNull(), genre: text("genre"), releaseYear: integer("release_year"), language: text("language"), playCount: bigint("play_count", { mode: "number" }).notNull().default(0), popularityScore: integer("popularity_score").notNull().default(0), clipStartSec: integer("clip_start_sec").notNull().default(0), sourceUrl: text("source_url").notNull(), license: text("license"), available: boolean("available").notNull().default(true), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() });
export const packs = pgTable("packs", { id: text("id").primaryKey(), slug: text("slug").notNull().unique(), name: text("name").notNull(), description: text("description").notNull(), genre: text("genre"), coverArt: text("cover_art").notNull() });
export const packTracks = pgTable("pack_tracks", { packId: text("pack_id").references(() => packs.id).notNull(), trackId: text("track_id").references(() => tracks.id).notNull() }, (table) => [primaryKey({ columns: [table.packId, table.trackId] })]);
export const dailyChallenges = pgTable("daily_challenges", { date: text("date").primaryKey(), trackId: text("track_id").references(() => tracks.id).notNull(), publishedAt: timestamp("published_at", { withTimezone: true }).notNull().defaultNow() });
export const dailyEntries = pgTable("daily_entries", { date: text("date").notNull(), guestId: uuid("guest_id").references(() => guests.id).notNull(), gameId: text("game_id").notNull(), revision: integer("revision").notNull(), state: jsonb("state").notNull(), solved: boolean("solved").notNull().default(false), completedAt: timestamp("completed_at", { withTimezone: true }) }, (table) => [primaryKey({ columns: [table.date, table.guestId] })]);
export const results = pgTable("game_results", { gameId: text("game_id").notNull(), guestId: uuid("guest_id").references(() => guests.id).notNull(), mode: text("mode").notNull(), packId: text("pack_id").notNull(), difficulty: integer("difficulty").notNull().default(0), score: integer("score").notNull(), solved: boolean("solved").notNull(), summary: jsonb("summary").notNull(), completedAt: timestamp("completed_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [primaryKey({ columns: [table.gameId, table.guestId] })]);
export const adminSessions = pgTable("admin_sessions", { tokenHash: text("token_hash").primaryKey(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull() });
