"use client";
import { useRouter } from "next/navigation";
import { useMutation, useQuery } from "@tanstack/react-query";
import { Controller, useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { Play, LogIn, Users, Swords } from "lucide-react";
import { roomSettingsSchema, type PackSummary, type RoomMode } from "@/shared/contracts";
import { packDisplayName } from "@/shared/music-source";
import { api, json, type LiveRoom } from "@/lib/api";
import { useGuest } from "@/hooks/use-guest";
import { errorMessage, number } from "@/lib/utils";
import { Input } from "./ui/input";
import { Label } from "./ui/label";
import { Button } from "./ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "./ui/select";

export type Settings = z.output<typeof roomSettingsSchema>;
export function RoomSettingsForm({ value, onSave, disabled = false, showSubmit = true, mode = "party", buttonLabel = "Save settings" }: { value: Settings; onSave: (value: Settings) => void; disabled?: boolean; showSubmit?: boolean; mode?: RoomMode; buttonLabel?: string }) {
  const packs = useQuery({ queryKey: ["packs"], queryFn: () => api<{ packs: PackSummary[] }>("/packs") });
  const form = useForm<z.input<typeof roomSettingsSchema>, unknown, Settings>({ resolver: zodResolver(roomSettingsSchema), values: value });
  return <form onSubmit={form.handleSubmit(onSave)} className="form-stack" data-testid="room-settings"><div className="grid gap-4 sm:grid-cols-2"><div><Label htmlFor="room-pack">Music pack</Label><Controller name="packId" control={form.control} render={({ field }) => <Select value={field.value} onValueChange={field.onChange} disabled={disabled}><SelectTrigger id="room-pack"><SelectValue /></SelectTrigger><SelectContent>{packs.data?.packs.filter(pack => pack.count >= (mode === "duel" ? 7 : 3)).map(pack => <SelectItem value={pack.id} key={pack.id}>{packDisplayName(pack)} · {number(pack.count)}</SelectItem>)}</SelectContent></Select>} /></div>{mode === "party" ? <div><Label htmlFor="room-rounds">Rounds</Label><Input type="number" id="room-rounds" min={3} max={30} disabled={disabled} {...form.register("rounds", { valueAsNumber: true })} />{form.formState.errors.rounds && <p className="form-error" role="alert">Choose 3–30 rounds.</p>}</div> : <div><Label>Rounds</Label><p className="flex min-h-12 items-center text-sm text-muted">7 · First correct answer wins</p></div>}<div><Label htmlFor="room-excerpt">Start listening from</Label><Controller name="excerptMode" control={form.control} render={({ field }) => <Select value={field.value} onValueChange={field.onChange} disabled={disabled}><SelectTrigger id="room-excerpt"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="curated">Curated excerpt</SelectItem><SelectItem value="start">Beginning of song or preview</SelectItem></SelectContent></Select>} /></div><div><Label>Listening stages</Label><p className="flex min-h-12 items-center text-xs text-muted">1 · 2 · 4 · 7 · 11 · 16 seconds</p></div></div>{showSubmit && <Button disabled={disabled} type="submit" variant={buttonLabel === "Save settings" ? "outline" : "default"} size="lg"><Play />{buttonLabel}</Button>}{packs.isError && <div className="error-notice" role="alert">Couldn’t load the packs. <button type="button" className="underline" onClick={() => void packs.refetch()}>Try again</button></div>}</form>;
}
const joinSchema = z.object({ code: z.string().trim().toUpperCase().regex(/^[A-Z0-9]{6}$/, "Use the six-character room code.") });
export function RoomEntrance({ mode, packId = "global-mix" }: { mode: RoomMode; packId?: string }) {
  const router = useRouter(); const guest = useGuest(); const join = useForm<z.input<typeof joinSchema>, unknown, z.output<typeof joinSchema>>({ resolver: zodResolver(joinSchema), defaultValues: { code: "" } });
  const create = useMutation({ mutationFn: (settings: Settings) => api<{ room: LiveRoom }>("/rooms", { method: "POST", body: json({ mode, settings }) }), onSuccess: ({ room }) => router.push(`/rooms/${room.code}`) });
  const joining = useMutation({ mutationFn: ({ code }: { code: string }) => api<{ room: LiveRoom }>(`/rooms/${code}/commands`, { method: "POST", body: json({ id: crypto.randomUUID(), kind: "join" }) }), onSuccess: ({ room }) => router.push(`/rooms/${room.code}`) });
  return <div className="grid items-start gap-6 md:grid-cols-[1.3fr_1fr]"><section className="panel"><div className="mb-6 flex items-center gap-3">{mode === "party" ? <Users className="size-5 text-lime" /> : <Swords className="size-5 text-lime" />}<h2 className="text-2xl">Start a private {mode === "party" ? "party" : "duel"}.</h2></div><RoomSettingsForm mode={mode} value={{ packId, rounds: mode === "duel" ? 7 : 10, timeLimitSec: 30, startClipSec: 1, excerptMode: "curated" }} onSave={value => create.mutate(value)} disabled={create.isPending || !guest.data} buttonLabel={create.isPending ? "Creating room…" : "Create room"} />{create.isError && <div className="error-notice mt-5" role="alert">{errorMessage(create.error)}</div>}<p className="mt-5 text-xs text-muted">{mode === "party" ? "2–24 players · 30 seconds per round" : "2 players · 7 rounds · 30 seconds each"}<br />Everyone gets the same songs. Invite friends with your room code.</p></section><form className="panel form-stack" onSubmit={join.handleSubmit(value => joining.mutate(value))}><h2 className="text-2xl">Got an invite?</h2><p className="text-sm text-muted">Enter the code and pull up a chair.</p><div><Label htmlFor="join-code">Room code</Label><Input id="join-code" placeholder="ABC123" autoComplete="off" maxLength={6} className="uppercase tracking-[.2em]" {...join.register("code")} />{join.formState.errors.code && <p className="form-error" role="alert">{join.formState.errors.code.message}</p>}</div><Button variant="outline" type="submit" disabled={joining.isPending || !guest.data}><LogIn />{joining.isPending ? "Joining…" : "Join room"}</Button>{joining.isError && <div className="error-notice" role="alert">{errorMessage(joining.error)}</div>}</form>{guest.isError && <div className="error-notice md:col-span-2" role="alert">Couldn’t open your guest profile. <button type="button" className="underline" onClick={() => void guest.refetch()}>Try again</button></div>}</div>;
}
