"use client";
import { useEffect, useId, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Search, Check, Disc3, X, LoaderCircle } from "lucide-react";
import { api, type SearchTrack } from "@/lib/api";
import { Command, CommandInput, CommandList, CommandEmpty, CommandItem } from "./ui/command";
import { Button } from "./ui/button";

export function SongSearch({ value, onSelect, disabled = false }: { value: SearchTrack | null; onSelect: (track: SearchTrack | null) => void; disabled?: boolean }) {
  const [query, setQuery] = useState(""); const [debounced, setDebounced] = useState(""); const id = useId();
  useEffect(() => { const timeout = setTimeout(() => setDebounced(query.trim()), 200); return () => clearTimeout(timeout); }, [query]);
  const results = useQuery({ queryKey: ["song-search", debounced], queryFn: ({ signal }) => api<{ tracks: SearchTrack[] }>(`/catalog/search?q=${encodeURIComponent(debounced)}&limit=12`, { signal }), enabled: debounced.length >= 2 && !disabled, staleTime: 30_000 });
  if (value) return <div className="flex min-h-14 items-center gap-3 rounded-xl border border-lime/70 bg-panel px-4 py-3" data-testid="selected-song"><Check className="size-5 shrink-0 text-lime" /><div className="min-w-0 flex-1"><strong className="block break-words text-sm">{value.title}</strong><span className="text-xs text-muted">{value.artist}</span></div><Button type="button" size="icon" variant="ghost" aria-label="Choose another song" disabled={disabled} onClick={() => { onSelect(null); setQuery(""); }}><X /></Button></div>;
  return <div><label className="sr-only" htmlFor={id}>Search a song or artist</label><Command shouldFilter={false} label="Search a song or artist" className="focus-within:ring-2 focus-within:ring-lime"><div className="flex items-center px-4"><Search className="size-5 shrink-0 text-muted" aria-hidden /><CommandInput id={id} value={query} onValueChange={setQuery} disabled={disabled} placeholder="Search a song or artist" maxLength={100} aria-describedby={`${id}-help`} aria-expanded={query.trim().length >= 2} /></div><CommandList className={query.trim().length >= 2 ? "max-h-64 overflow-y-auto border-t border-border p-2" : "hidden"} data-testid="song-suggestions">{query.trim().length >= 2 && <>{results.isFetching && <p className="flex gap-2 p-3 text-sm text-muted" role="status"><LoaderCircle className="size-4 motion-safe:animate-spin" />Finding songs…</p>}{results.isError ? <p role="alert" className="p-3 text-sm text-[#ffb9ac]">Couldn’t search songs.<button type="button" className="ml-2 underline" onClick={() => void results.refetch()}>Try again</button></p> : <><CommandEmpty className="p-3 text-sm text-muted">{results.isLoading || debounced !== query.trim() ? "Finding songs…" : "No songs found. Try a different artist or title."}</CommandEmpty>{results.data?.tracks.map(track => <CommandItem value={track.id} key={track.id} onSelect={() => onSelect(track)}><Disc3 className="size-5 shrink-0 text-muted" /><span className="min-w-0"><span className="block break-words text-sm">{track.title}</span><span className="text-xs text-muted">{track.artist}</span></span></CommandItem>)}</>}</>}</CommandList></Command><p id={`${id}-help`} className="mt-2 text-[11px] text-muted">Type at least 2 characters. Choose a song, then submit your guess.</p></div>;
}
