"use client";
import * as React from "react";
import * as Primitive from "@radix-ui/react-tabs";
import { cn } from "@/lib/utils";
export const Tabs = Primitive.Root;
export const TabsList = React.forwardRef<React.ComponentRef<typeof Primitive.List>, React.ComponentPropsWithoutRef<typeof Primitive.List>>(({ className, ...props }, ref) => <Primitive.List ref={ref} className={cn("flex flex-wrap gap-1 border-b border-border pb-3", className)} {...props} />);
TabsList.displayName = "TabsList";
export const TabsTrigger = React.forwardRef<React.ComponentRef<typeof Primitive.Trigger>, React.ComponentPropsWithoutRef<typeof Primitive.Trigger>>(({ className, ...props }, ref) => <Primitive.Trigger ref={ref} className={cn("min-h-11 rounded-lg px-5 py-3 text-sm text-muted outline-none focus-visible:ring-2 focus-visible:ring-lime data-[state=active]:bg-lime data-[state=active]:text-charcoal", className)} {...props} />);
TabsTrigger.displayName = "TabsTrigger";
export const TabsContent = React.forwardRef<React.ComponentRef<typeof Primitive.Content>, React.ComponentPropsWithoutRef<typeof Primitive.Content>>(({ className, ...props }, ref) => <Primitive.Content ref={ref} className={cn("mt-6 outline-none focus-visible:ring-2 focus-visible:ring-lime", className)} {...props} />);
TabsContent.displayName = "TabsContent";
